const apologiesList = [
  "Minha mãe me chamou para jogar Pokemon GO, não vai rolar live",
  "Levei a Lalra para sair, mas amanhã tem Splatoon",
  "Hoje tem Outback",
  "Fiquei preso em uma reunião do serviço, mas amanhã tem Unite",
  "Hoje foi muito cansativo no serviço, mas amanhã tem soul link com o furipe",
  "Caiu a internet pessoal",
  "Meu gás deu problema e minha cozinha explodiu",
  "Comecei a assistir Stranger Things e agora estou com medo, não tem live hoje",
  "Entrou um passáro dentro de casa, vou ter que cuidar, amanhã tem live",
  "Hoje tem gravação do Project N, não vou poder",
  "Estou com o meu advogado assinando o contrato com o Ultra N, amanhã tem Animal Crossing com a Lalra",
  "Meu nariz está sangrando",
  "Vou pegar uma camisa da Nintendo que meu amigo trouxe de NY",
  "Hoje tem gravação do Clube do Disquete",
  "Rio de Janeiro",
  "Preciso organizar coisas do canal, amanhã tem Smash",
  "Domingo já teve",
  "Segunda-feira já teve",
  "Terça-feira já teve",
  "Quarta-feira já teve",
  "Quinta-feira já teve",
  "Sexta-feira já teve",
  "Sábado já teve",
  "Hoje é feriado",
  "Hoje é feriado em Nova Iguaçu",
  "O Eduardo veio aqui em casa e ele tá usando o switch",
  "Hoje não dá a Lisa comeu meu pc, amanhã pode ter Overcooked",
  "Tô arrumando as coisas da mudança o dia todo, 17h eu abro uma salinha no Mario kart e a gente joga só pra não ficar sem jogar aí mais pra noite jogo o gang beasts",
  "Tive que pintar uma parede",
  "Gente, cheguei agora de uma reunião e to completamente sem condições de abrir live :( Amanhã tem mario strikers",
  "Passei o dia inteiro vendo video de auto ajuda, hoje vou contemplar a vida, amanhã tem live de Quiz da Capricho",
  "Sem live porque não quero hoje",
  "Gente, vou sair pra jantar com a minha mãe hj e depois tem project N então sem live hj :(",
  "Gente, hj sem Live pq tô com sinusite ai tô dando um tempinho ❤️ amanhã tem com a laura ❤️",
  "Gente, não tá tendo live hj pq eu vou participar da live em outro canal",
  "Gente, sem live hj :/ Vim na minha mãe e isso me atrasou todo",
  "Mais um dia sem Live gente",
  "Lembrando q hj não vai ter live, ta bom? Tá vindo o cara aqui desmontar umas coisas então eu vou ter q ficar ajudando",
  "Hoje tem Mengão",
  "Hoje a Live vai acabar mais cedo gente, tenho Project N pra gravar",
  "Fiquei assistindo Malhação do Fiuk até tarde",
  "Fui jogar Pokemon GO com desconhecidos e levaram meu celular",
  "Joguei Sonic o domingo inteiro, minha retina descolou",
  "Fiz um quiz para saber qual tartaruga eu sou, deu Leonardo, vou ver video de auto ajuda agora",
  "Fiquei 1h explicando pro Padre como Sunshine é bom, sem live hoje",
  "Perdi a hora jogando Donkey Konga, amanhã tem, taiko no tatsujin",
  "Tropecei no meu Ring fit, vou ficar me recuperando pessoal",
  "Tentei jogar Xenoblade, agora estou bravo, sem live hoje",
  "Já teve live de manhã",
  "Fui no aniversário do Guanabara, não sei se estou vivo",
  "Meu croma parou de funcionar", 
  "Jogamos Switch Sports a noite toda ontem, hoje estou morto",
  "Joguei Diablo sozinho hoje, agora estou indo na casa do Padre Edson",
  "Estou aprendendo a fazer arroz",
  "Estou fazendo feijão, como não uso panela de pressão vai demorar, sem live hoje",
  "Fui aprender a usar panela de pressão, explodi minha cozinha",
  "Fui em uma exposição psicodélica com a Lalra",
  "Tive que ensaiar com a minha banda hoje, amanhã tem Legião Urbana na live"
];

export default apologiesList;